#!/bin/bash

layout=$(setxkbmap -query | perl -ne 'print "$1\n" if /layout: *(.*)/');
if [[ $layout == "dvp" ]]; then setxkbmap ru -variant slavonic-dvorak; fi
if [[ $layout == "ru" ]]; then setxkbmap dvp; fi
